# Generated by Django 5.2 on 2025-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='purchase_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
