# Generated by Django 5.2 on 2025-05-13 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
