# Generated by Django 5.2 on 2025-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_user_details_purchase_number_user_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
