# Generated by Django 5.2 on 2025-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_user_details_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderkey', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='purchase_number',
            field=models.IntegerField(default=0),
        ),
    ]
